# https://github.com/lowlighter/metrics/blob/latest/.github/readme/partials/documentation/setup/action.md
name: Metrics
on:
  # Schedule updates
  schedule: [{cron: "30 11,16,21 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  # Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # https://github.com/lowlighter/metrics/blob/latest/source/plugins/core/README.md
          user: chungxon
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_timezone: Asia/Ho_Chi_Minh
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 48
          plugin_activity_load: 300
          plugin_activity_timestamps: yes
          plugin_activity_visibility: all
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_indepth: yes
          plugin_followup_sections: repositories
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 100
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_self: yes
          plugin_notable_types: commit
          plugin_reactions: yes
          plugin_reactions_display: absolute
          plugin_reactions_limit: 200
          plugin_reactions_limit_discussions: 100
          plugin_reactions_limit_discussions_comments: 100
          plugin_reactions_limit_issues: 100
          plugin_support: yes
          plugin_traffic: yes
          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: chung_xon
